"""``surface.lock`` build / read / write / diff (F-LOCK-*)."""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import tomli_w

from .registry import Registry
from .scanners import ScanResult

__all__ = [
    "LOCKFILE_NAME",
    "Diff",
    "DiffEntry",
    "LockMcp",
    "LockModel",
    "LockPrompt",
    "LockTool",
    "Lockfile",
    "build_lock",
    "diff_locks",
    "read_lock",
    "write_lock",
]

LOCKFILE_NAME = "surface.lock"

HEADER = (
    "# surface.lock — generated by surfacelock. Review changes like package-lock.json.\n"
    "# Run `surfacelock update` after an intentional change to the AI surface.\n"
)


@dataclass
class LockModel:
    name: str
    provider: str
    kind: str
    resolved: str
    floating: bool
    known: bool
    locations: list[str] = field(default_factory=list)
    deprecation: str | None = None
    retirement: str | None = None
    price_in_per_1m: float | None = None
    price_out_per_1m: float | None = None

    def to_toml(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            "name": self.name,
            "provider": self.provider,
            "kind": self.kind,
            "resolved": self.resolved,
            "floating": self.floating,
            "known": self.known,
            "locations": list(self.locations),
        }
        if self.deprecation:
            data["deprecation"] = self.deprecation
        if self.retirement:
            data["retirement"] = self.retirement
        if self.price_in_per_1m is not None:
            data["price_in_per_1m"] = self.price_in_per_1m
        if self.price_out_per_1m is not None:
            data["price_out_per_1m"] = self.price_out_per_1m
        return data


@dataclass
class LockPrompt:
    id: str
    path: str
    line: int
    sha256: str
    chars: int
    approx_tokens: int
    source: str
    owners: list[str] = field(default_factory=list)

    def to_toml(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            "id": self.id,
            "path": self.path,
            "line": self.line,
            "sha256": self.sha256,
            "chars": self.chars,
            "approx_tokens": self.approx_tokens,
            "source": self.source,
        }
        if self.owners:
            data["owners"] = list(self.owners)
        return data


@dataclass
class LockTool:
    name: str
    path: str
    line: int
    sha256: str
    source: str
    description: str = ""
    param_keys: list[str] = field(default_factory=list)

    def to_toml(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "path": self.path,
            "line": self.line,
            "sha256": self.sha256,
            "source": self.source,
            "description": self.description,
            "param_keys": list(self.param_keys),
        }


@dataclass
class LockMcp:
    name: str
    path: str
    transport: str
    url: str = ""
    command: str = ""
    args: list[str] = field(default_factory=list)
    env_keys: list[str] = field(default_factory=list)
    sha256: str = ""

    def to_toml(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "path": self.path,
            "transport": self.transport,
            "url": self.url,
            "command": self.command,
            "args": list(self.args),
            "env_keys": list(self.env_keys),
            "sha256": self.sha256,
        }


@dataclass
class Lockfile:
    surfacelock_version: str
    registry_updated: str
    scan_config_hash: str
    counts: dict[str, int]
    models: list[LockModel] = field(default_factory=list)
    prompts: list[LockPrompt] = field(default_factory=list)
    tools: list[LockTool] = field(default_factory=list)
    mcp_servers: list[LockMcp] = field(default_factory=list)

    def to_toml(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            "meta": {
                "surfacelock_version": self.surfacelock_version,
                "registry_updated": self.registry_updated,
                "scan_config_hash": self.scan_config_hash,
                "counts": dict(self.counts),
            }
        }
        if self.models:
            data["model"] = [m.to_toml() for m in self.models]
        if self.prompts:
            data["prompt"] = [p.to_toml() for p in self.prompts]
        if self.tools:
            data["tool"] = [t.to_toml() for t in self.tools]
        if self.mcp_servers:
            data["mcp_server"] = [m.to_toml() for m in self.mcp_servers]
        return data


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
def _model_entry(finding: Any, registry: Registry, pinned: str | None) -> LockModel:
    name = finding.name
    info = registry.get(name)
    resolved_info = registry.resolve(name)
    floating, _reason = registry.is_floating(name)
    known = name in registry

    snapshot = pinned
    if snapshot is None:
        snapshot = registry.resolved_snapshot(name) or name

    terminal = resolved_info or info
    provider = (info.provider if info else None) or (
        terminal.provider if terminal else (finding.provider or "unknown")
    )
    kind = terminal.kind if terminal and terminal.kind != "deployment" else finding.context
    if info is not None and info.kind == "deployment":
        kind = "deployment"
    if info is not None and info.kind != "chat":
        kind = info.kind

    deprecation = None
    retirement = None
    for source_info in (terminal, info):
        if source_info is None:
            continue
        deprecation = deprecation or source_info.deprecation
        retirement = retirement or source_info.retirement

    price_in = terminal.price_in if terminal else None
    price_out = terminal.price_out if terminal else None

    return LockModel(
        name=name,
        provider=provider,
        kind=kind,
        resolved=snapshot,
        floating=floating,
        known=known,
        locations=[f"{finding.file}:{finding.line}"],
        deprecation=deprecation,
        retirement=retirement,
        price_in_per_1m=price_in,
        price_out_per_1m=price_out,
    )


def build_lock(
    result: ScanResult,
    registry: Registry,
    *,
    version: str,
    previous: Lockfile | None = None,
    resolve: set[str] | None = None,
) -> Lockfile:
    """Turn a scan result into a lockfile.

    Existing pins are preserved (F-LOCK-2).  ``resolve`` names — or the single
    element ``{"all"}`` — are deliberately re-pinned to the registry's current
    resolution.
    """
    resolve = resolve or set()
    previous_models: dict[str, LockModel] = {}
    previous_prompts: dict[str, LockPrompt] = {}
    if previous is not None:
        previous_models = {m.name: m for m in previous.models}
        previous_prompts = {p.id: p for p in previous.prompts}

    merged_models: dict[str, LockModel] = {}
    for finding in result.models:
        prior = previous_models.get(finding.name)
        keep = None
        if prior is not None and "all" not in resolve and finding.name not in resolve:
            keep = prior.resolved
        entry = _model_entry(finding, registry, keep)
        existing = merged_models.get(finding.name)
        if existing is None:
            merged_models[finding.name] = entry
        else:
            for loc in entry.locations:
                if loc not in existing.locations:
                    existing.locations.append(loc)
            existing.locations.sort()

    models = sorted(merged_models.values(), key=lambda m: m.name)
    prompts = sorted(
        (
            LockPrompt(
                id=p.id,
                path=p.path,
                line=p.line,
                sha256=p.sha256,
                chars=p.chars,
                approx_tokens=p.approx_tokens,
                source=p.source,
                owners=list(p.owners)
                or (previous_prompts[p.id].owners if p.id in previous_prompts else []),
            )
            for p in result.prompts
        ),
        key=lambda p: p.id,
    )
    tools = sorted(
        (
            LockTool(
                name=t.name,
                path=t.file,
                line=t.line,
                sha256=t.sha256,
                source=t.source,
                description=t.description,
                param_keys=list(t.param_keys),
            )
            for t in result.tools
        ),
        key=lambda t: (t.path, t.name),
    )
    mcp_servers = sorted(
        (
            LockMcp(
                name=m.name,
                path=m.path,
                transport=m.transport,
                url=m.url,
                command=m.command,
                args=list(m.args),
                env_keys=list(m.env_keys),
                sha256=m.sha256,
            )
            for m in result.mcp_servers
        ),
        key=lambda m: (m.path, m.name),
    )

    return Lockfile(
        surfacelock_version=version,
        registry_updated=registry.updated,
        scan_config_hash=result.config_hash,
        counts={
            "models": len(models),
            "prompts": len(prompts),
            "tools": len(tools),
            "mcp_servers": len(mcp_servers),
        },
        models=models,
        prompts=prompts,
        tools=tools,
        mcp_servers=mcp_servers,
    )


# ---------------------------------------------------------------------------
# IO
# ---------------------------------------------------------------------------
def write_lock(path: Path, lock: Lockfile) -> None:
    body = tomli_w.dumps(lock.to_toml())
    path.write_text(HEADER + body, encoding="utf-8")


def read_lock(path: Path) -> Lockfile:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    meta = data.get("meta", {})
    counts = meta.get("counts", {})
    return Lockfile(
        surfacelock_version=str(meta.get("surfacelock_version", "")),
        registry_updated=str(meta.get("registry_updated", "")),
        scan_config_hash=str(meta.get("scan_config_hash", "")),
        counts={str(k): int(v) for k, v in counts.items()},
        models=[LockModel(**m) for m in data.get("model", [])],
        prompts=[LockPrompt(**p) for p in data.get("prompt", [])],
        tools=[LockTool(**t) for t in data.get("tool", [])],
        mcp_servers=[LockMcp(**m) for m in data.get("mcp_server", [])],
    )


# ---------------------------------------------------------------------------
# Diff
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class DiffEntry:
    kind: str  # model | prompt | tool | mcp_server
    action: str  # added | removed | changed
    name: str
    detail: str = ""


@dataclass
class Diff:
    entries: list[DiffEntry] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.entries)

    def by_kind(self, kind: str) -> list[DiffEntry]:
        return [e for e in self.entries if e.kind == kind]


def _index(items: list[Any], key: Any) -> dict[Any, Any]:
    return {key(i): i for i in items}


def diff_locks(old: Lockfile | None, new: Lockfile) -> Diff:
    """Compare two lockfiles.  ``old`` may be ``None`` (everything is added)."""
    entries: list[DiffEntry] = []

    def compare(
        kind: str,
        old_items: list[Any],
        new_items: list[Any],
        key: Any,
        compare_field: Any,
        describe: Any,
    ) -> None:
        old_map = _index(old_items, key)
        new_map = _index(new_items, key)
        for k in sorted(new_map, key=str):
            if k not in old_map:
                entries.append(DiffEntry(kind, "added", str(k), describe(new_map[k])))
            elif compare_field(old_map[k]) != compare_field(new_map[k]):
                entries.append(DiffEntry(kind, "changed", str(k), describe(new_map[k], old_map[k])))
        for k in sorted(old_map, key=str):
            if k not in new_map:
                entries.append(DiffEntry(kind, "removed", str(k), describe(old_map[k])))

    compare(
        "model",
        old.models if old else [],
        new.models,
        lambda m: m.name,
        lambda m: m.resolved,
        lambda n, o=None: (
            f"{o.resolved} → {n.resolved}" if o is not None else f"pinned to {n.resolved}"
        ),
    )
    compare(
        "prompt",
        old.prompts if old else [],
        new.prompts,
        lambda p: p.id,
        lambda p: p.sha256,
        lambda n, o=None: (
            f"{o.approx_tokens} → {n.approx_tokens} tokens ({n.approx_tokens - o.approx_tokens:+d})"
            if o is not None
            else f"{n.approx_tokens} tokens"
        ),
    )
    compare(
        "tool",
        old.tools if old else [],
        new.tools,
        lambda t: (t.path, t.name),
        lambda t: t.sha256,
        lambda n, o=None: f"schema {n.sha256[:8]}",
    )
    compare(
        "mcp_server",
        old.mcp_servers if old else [],
        new.mcp_servers,
        lambda m: (m.path, m.name),
        lambda m: m.sha256,
        lambda n, o=None: f"{n.transport} {n.url or n.command}".strip(),
    )

    entries.sort(key=lambda e: (e.kind, e.name))
    return Diff(entries=entries)
