"""Lockfile: build, pin-keeping, IO round-trip, diff engine."""

from __future__ import annotations

from pathlib import Path

from surfacelock.lockfile import (
    Lockfile,
    LockModel,
    build_lock,
    diff_locks,
    read_lock,
    write_lock,
)
from surfacelock.registry import Registry
from surfacelock.scanners import scan

VERSION = "0.1.0"


def _lock_for(root: Path, registry: Registry, **kw: object) -> Lockfile:
    result = scan(root, registry=registry)
    return build_lock(result, registry, version=VERSION, **kw)  # type: ignore[arg-type]


def test_build_lock_counts(python_openai: Path) -> None:
    registry = Registry.load()
    lock = _lock_for(python_openai, registry)
    assert lock.counts["models"] >= 2
    assert lock.counts["prompts"] >= 1
    assert lock.counts["tools"] >= 1
    assert lock.surfacelock_version == VERSION
    assert lock.registry_updated == registry.updated


def test_floating_alias_is_pinned_on_init(python_openai: Path) -> None:
    registry = Registry.load()
    lock = _lock_for(python_openai, registry)
    gpt4o = next(m for m in lock.models if m.name == "gpt-4o")
    assert gpt4o.floating is True
    assert gpt4o.resolved == "gpt-4o-2024-08-06"
    assert gpt4o.known is True
    assert gpt4o.price_in_per_1m == 2.5


def test_existing_pin_is_kept_even_if_registry_moves(python_openai: Path) -> None:
    registry = Registry.load()
    previous = _lock_for(python_openai, registry)
    # Simulate a stale pin from an older registry.
    previous.models[0].resolved = "gpt-4o-2024-05-13"
    previous.models[0].name = "gpt-4o"
    fresh = _lock_for(python_openai, registry, previous=previous)
    gpt4o = next(m for m in fresh.models if m.name == "gpt-4o")
    assert gpt4o.resolved == "gpt-4o-2024-05-13", "a lockfile must not silently re-pin"


def test_resolve_all_repins(python_openai: Path) -> None:
    registry = Registry.load()
    previous = _lock_for(python_openai, registry)
    for model in previous.models:
        if model.name == "gpt-4o":
            model.resolved = "gpt-4o-2024-05-13"
    fresh = _lock_for(python_openai, registry, previous=previous, resolve={"all"})
    gpt4o = next(m for m in fresh.models if m.name == "gpt-4o")
    assert gpt4o.resolved == "gpt-4o-2024-08-06"


def test_resolve_single_model(python_openai: Path) -> None:
    registry = Registry.load()
    previous = _lock_for(python_openai, registry)
    for model in previous.models:
        model.resolved = "stale-snapshot"
    fresh = _lock_for(python_openai, registry, previous=previous, resolve={"gpt-4o"})
    gpt4o = next(m for m in fresh.models if m.name == "gpt-4o")
    assert gpt4o.resolved == "gpt-4o-2024-08-06"
    others = [m for m in fresh.models if m.name != "gpt-4o"]
    assert all(m.resolved == "stale-snapshot" for m in others)


def test_locations_merge_for_repeated_model(tmp_path: Path) -> None:
    (tmp_path / "a.py").write_text('model = "gpt-4o"\n', encoding="utf-8")
    (tmp_path / "b.py").write_text('model = "gpt-4o"\n', encoding="utf-8")
    lock = _lock_for(tmp_path, Registry.load())
    gpt4o = next(m for m in lock.models if m.name == "gpt-4o")
    assert gpt4o.locations == ["a.py:1", "b.py:1"]


def test_write_read_roundtrip(tmp_path: Path, python_openai: Path) -> None:
    registry = Registry.load()
    lock = _lock_for(python_openai, registry)
    path = tmp_path / "surface.lock"
    write_lock(path, lock)
    again = read_lock(path)
    assert again.models == lock.models
    assert again.prompts == lock.prompts
    assert again.tools == lock.tools
    assert again.counts == lock.counts


def test_lockfile_has_header_and_no_body_timestamp(tmp_path: Path, python_openai: Path) -> None:
    lock = _lock_for(python_openai, Registry.load())
    path = tmp_path / "surface.lock"
    write_lock(path, lock)
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# surface.lock — generated by surfacelock.")
    assert "generated_at" not in text


def test_lockfile_is_deterministic(tmp_path: Path, python_openai: Path) -> None:
    registry = Registry.load()
    a = tmp_path / "a.lock"
    b = tmp_path / "b.lock"
    write_lock(a, _lock_for(python_openai, registry))
    write_lock(b, _lock_for(python_openai, registry))
    assert a.read_text(encoding="utf-8") == b.read_text(encoding="utf-8")


def test_diff_detects_model_snapshot_change() -> None:
    old = Lockfile(
        "0.1.0",
        "2026-01-01",
        "h",
        {"models": 1},
        models=[LockModel("gpt-4o", "openai", "chat", "gpt-4o-2024-05-13", True, True)],
    )
    new = Lockfile(
        "0.1.0",
        "2026-01-01",
        "h",
        {"models": 1},
        models=[LockModel("gpt-4o", "openai", "chat", "gpt-4o-2024-08-06", True, True)],
    )
    diff = diff_locks(old, new)
    assert diff.changed
    entry = diff.entries[0]
    assert entry.kind == "model"
    assert entry.action == "changed"
    assert "2024-05-13" in entry.detail and "2024-08-06" in entry.detail


def test_diff_reports_added_and_removed() -> None:
    from surfacelock.lockfile import LockPrompt

    old = Lockfile(
        "0.1.0", "d", "h", {}, prompts=[LockPrompt("a", "x.py", 1, "s1", 10, 3, "inline")]
    )
    new = Lockfile(
        "0.1.0", "d", "h", {}, prompts=[LockPrompt("b", "y.py", 1, "s2", 20, 6, "inline")]
    )
    diff = diff_locks(old, new)
    actions = {(e.action, e.name) for e in diff.entries}
    assert ("added", "b") in actions
    assert ("removed", "a") in actions


def test_diff_prompt_detail_includes_token_delta() -> None:
    from surfacelock.lockfile import LockPrompt

    old = Lockfile(
        "0.1.0", "d", "h", {}, prompts=[LockPrompt("p", "x.py", 1, "s1", 10, 100, "inline")]
    )
    new = Lockfile(
        "0.1.0", "d", "h", {}, prompts=[LockPrompt("p", "x.py", 1, "s2", 20, 141, "inline")]
    )
    diff = diff_locks(old, new)
    assert "+41" in diff.entries[0].detail


def test_diff_against_none_marks_everything_added(python_openai: Path) -> None:
    lock = _lock_for(python_openai, Registry.load())
    diff = diff_locks(None, lock)
    assert diff.entries
    assert all(e.action == "added" for e in diff.entries)
